### ISSUE TITLE
raw text should not be allowed.

### ISSUE THREAD

**Issue by danmarsden** [lchamney/moodle-block_return#5]
your block config allows users (including students on their dashboard pages) to add raw html content to the block (including javascript.) that is not santised or cleaned when including it in the output.
Please take a look at:
https://docs.moodle.org/dev/Security#Don.27t_trust_any_input_from_users
and:
https://docs.moodle.org/dev/Security#Clean_and_escape_data_before_output

thanks!

**Comment by lchamney** [comment]
Hi, sorry about the delay. I've addressed the other issues, but I'm not sure I understand. The config page only seems to have a checkbox, not a text input. Can you show me where the raw text is?

Thanks for all your help!

**Comment by mudrd8mz** [comment]
I think it's the fact that you have the checkbox field's type set to `PARAM_RAW` is what is confusing here. 

For dropdowns and checkboxes, there is no point to specify the type, if I recall correctly.

**Comment by lchamney** [comment]
It looks like it, there isn't a PARAM type for booleans.

Thanks, it's fixed now. I just removed the setType() line altogether.

@danmarsden, does this address the issue?

**Comment by danmarsden** [comment]
I dont' remember what I was complaining about here... and I can't see antything in your existing code that might be what this was... I'm guessing David is right and I just saw "PARAM_RAW" without looking too closely at the context.. lets just close it ;-)
