### ISSUE TITLE
SQL compatibility

### ISSUE THREAD

**Issue by mudrd8mz** [lchamney/moodle-block_return#6]
https://github.com/lchamney/moodle-block_return/blob/151d2955de870ff4c861f5250b48d76918083dda/block_return.php#L71

Have you tested this on PostgreSQL? From what I remember, the double quotes in the query will cause troubles as the DB will interpret it not as a string but as an identifier.

**Comment by mudrd8mz** [comment]
Ref: https://www.prisma.io/dataguide/postgresql/short-guides/quoting-rules#double-quotes

**Comment by lchamney** [comment]
I didn't! Thanks, it's fixed now (by reversing the single and double quotes).
