### ISSUE TITLE
php end tag shouldn't be here.

### ISSUE THREAD

**Issue by danmarsden** [lchamney/moodle-block_return#7]
https://github.com/lchamney/moodle-block_return/blob/d3e5addb6ad50549ac3b3125462f39f194ce0abb/lang/en/block_return.php#L35

Moodle doesn't use closing tags at the end of files - best to remove this.

**Comment by danmarsden** [comment]
another one here:
https://github.com/lchamney/moodle-block_return/blob/main/db/access.php#L50

**Comment by lchamney** [comment]
Fixed, thanks!
